version: '3.11'

services:
  redis:
    image: redis:7.0.12
    hostname: redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fso_network
    container_name: fso-redis
    volumes:
      - ./app/redis:/data

  nginx:
    image: nginx
    ports:
      - "8081:8081"
    container_name: fso-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - fso_network

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - fso_network
    container_name: fso-server
    command: /start.sh

networks:
  fso_network: